networks:
  toubilibhexa.net:
    driver: bridge

services:

  #
  # service 
  api.toubilibhexa:
    image: 'operrin/php:8.5.6'
    env_file: ./toubilib.env
    ports:
      - '6080:80'
    volumes:
      - ./app:/var/php
    working_dir: /var/php
    networks:
      - toubilibhexa.net
    depends_on:
      toubilib.db:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c", "composer install --no-interaction && php -S 0.0.0.0:80 -t /var/php/public"]

  #
  # service db : base de données postgresql
  toubilib.db:
    image: 'postgres:18.3'
    env_file: ./toubilibdb.env
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 5s
      retries: 5 
    networks:
      - toubilibhexa.net
    volumes:
      - ./app/sql:/var/lib/postgresql

  #
  # service administration des bases sql
  adminer:
    image: adminer:5.4.2
    ports:
      - '8080:8080'
    networks:
      - toubilibhexa.net

  #
  # composer
#  composer:
#    image: composer:2.10.1
#    command: ["composer", "install"]
#    networks:
#      - toubilibhexa.net
#    volumes:
#      - ./app:/app
#    depends_on:
#      - api.toubilibhexa

